name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: chmod 777 run.sh && Now=$(date +"%m-%d-%y-%H-%M-%S") && docker build . --file Dockerfile -t ovaledge.jfrog.io/ovaledge-docker-local/ovaledge:20 && docker login ovaledge.jfrog.io -u shivaprasad.mergu@ovaledge.com -p 0valEdge! && docker push ovaledge.jfrog.io/ovaledge-docker-local/ovaledge:20
